export { AdvantagesBlock } from './advantages'
export { AppointmentBlock } from './appointment'
export { ChooseBlock } from './choose'
export { CommandBlock } from './command'
export { GlobalBlock } from './global'
export { ReviewsBlock } from './reviews'
export { UniqueBlock } from './unique-block'
export { Wave } from './wave'
